/**
 * Generates /public/img (AVIF + WebP, multiple widths) and lib/images.ts.
 *
 * Widths in the manifest are the REAL output widths, read back from the encoded
 * files — never the requested ones. Sources vary in size and are never upscaled,
 * so a requested 2000w can land at 1282w; advertising the requested number in a
 * srcset descriptor makes the browser pick a smaller file than it asked for.
 */
import sharp from 'sharp';
import fs from 'fs';

const SRC = 'src-assets';
const OUT = 'public/img';

/**
 * `extract` crops are taken before resizing. They exist so a photograph used in
 * more than one place is framed differently each time — a hero macro is not the
 * same picture as the dish card it also feeds.
 */
const JOBS = [
  // Hero: the dining room, cropped to a wide band.
  //
  // Not a plate. The room is the differentiator that no competitor can copy and
  // no stock library can fake — chandeliers, teal curtains, gold leaf, navy
  // banquettes — and it is where the site's whole palette comes from. Its dark
  // left third gives the headline somewhere to sit without a heavy scrim.
  //
  // Cropped from DSC00253 at the source's full 2304px width. The newer room
  // photograph found in the old site's JS bundle composes better but only
  // survives a 1860px crop, which is too soft for full bleed; it carries the
  // Experience band instead, so the homepage never repeats a room shot.
  { file: 'DSC00253.jpg',          slug: 'hero',     want: [2304, 1600, 1000],
    extract: { left: 0, top: 230, width: 2304, height: 1100 } },

  // The room photograph recovered from the old site's bundle — never published
  // at any size. Chandeliers and gold-leaf columns, no bar clutter in frame.
  { file: 'room-wide.jpg',         slug: 'roomwide', want: [1860, 1200, 760],
    extract: { left: 0, top: 230, width: 1860, height: 886 } },
  { file: 'location.jpg',          slug: 'spread',   want: [1282, 900] },

  // Signature dishes, using the kitchen's own photograph of each dish rather
  // than a crop guessed out of a group shot. Landscape sources, so the cards
  // are framed 5:4 instead of 4:5.
  { file: 'd-sesame.jpg',          slug: 'sesame',   want: [1400, 900, 560] },
  { file: 'd-chili.jpg',           slug: 'chili',    want: [1400, 900, 560] },
  { file: 'd-beef.jpg',            slug: 'beef',     want: [1400, 900, 560] },
  { file: 'd-kungpao.jpg',         slug: 'kungpao',  want: [1400, 900, 560] },
  { file: 'd-chowmein.jpg',        slug: 'chowmein', want: [1400, 900, 560] },
  { file: 'd-burger.jpg',          slug: 'burger',   want: [1400, 900, 560] },
  { file: 'DSC00253.jpg',          slug: 'room',     want: [2000, 1400, 900] },
  { file: 'DSC00244.jpg',          slug: 'table',    want: [1600, 1100, 700] },
  { file: 'tableNumber.jpg',       slug: 'detail',   want: [1600, 1100, 700] },
];

fs.mkdirSync(OUT, { recursive: true });
// Clear only this script's own output. The brand mark in here is produced by
// build-logo.mjs and must survive a photo rebuild.
const OWNED = /-\d+\.(avif|webp)$/;
for (const f of fs.readdirSync(OUT)) if (OWNED.test(f)) fs.unlinkSync(`${OUT}/${f}`);

const manifest = {};

for (const { file, slug, want, extract } of JOBS) {
  const src = `${SRC}/${file}`;
  const base = () => {
    const p = sharp(src).rotate();
    return extract ? p.extract(extract) : p;
  };
  const meta = await base().metadata();
  // metadata() on a pipeline reports the source size, so trust the crop when set.
  const natural = extract ? extract.width : meta.width;

  // Drop requested widths we cannot reach, and de-duplicate at the cap.
  const widths = [...new Set(want.map((w) => Math.min(w, natural)))].sort((a, b) => b - a);

  const entries = [];
  for (const w of widths) {
    await base().resize({ width: w }).avif({ quality: 58, effort: 5 }).toFile(`${OUT}/${slug}-${w}.avif`);
    await base().resize({ width: w }).webp({ quality: 82 }).toFile(`${OUT}/${slug}-${w}.webp`);
    entries.push(w);
  }

  const probe = await sharp(`${OUT}/${slug}-${widths[0]}.webp`).metadata();
  const blur = await base().resize({ width: 20 }).webp({ quality: 40 }).toBuffer();

  manifest[slug] = {
    widths: entries,
    w: probe.width,
    h: probe.height,
    blur: `data:image/webp;base64,${blur.toString('base64')}`,
  };
  console.log(slug.padEnd(9), `natural ${natural}px ->`, entries.join(', '));
}

const ts = `// AUTO-GENERATED by build-images.mjs — do not edit by hand.
// Widths are real encoded output widths, so srcset descriptors never lie.
export type ImageMeta = { widths: number[]; w: number; h: number; blur: string };
export const IMAGES: Record<string, ImageMeta> = ${JSON.stringify(manifest, null, 1)};
export type ImageSlug = keyof typeof IMAGES;
`;
fs.writeFileSync('lib/images.ts', ts);
console.log('\nwrote lib/images.ts');
