import { IMAGES } from '@/lib/images';

type Props = {
  /** Key in lib/images.ts (generated by build-images.mjs). */
  slug: string;
  alt: string;
  sizes: string;
  className?: string;
  priority?: boolean;
  /** object-position, for art-directing a crop inside a fixed frame. */
  position?: string;
  /**
   * Cover the parent box instead of sizing to the image's own aspect ratio.
   * Only for parents with a definite height (hero, page heads, fixed frames).
   */
  fill?: boolean;
};

/**
 * Responsive AVIF/WebP picture backed by the generated manifest.
 *
 * Hand-rolled rather than next/image: every source is a local, pre-encoded
 * static file, so there is nothing to optimise at request time — no optimizer
 * route to expose, cache, or pay for. Intrinsic width/height come from the
 * manifest so the browser reserves the right box and the page never shifts.
 */
export default function Img({ slug, alt, sizes, className, priority, position, fill }: Props) {
  const meta = IMAGES[slug];
  if (!meta) throw new Error(`Unknown image slug "${slug}" — run: node build-images.mjs`);

  const { widths, w, h, blur } = meta;
  const srcset = (ext: string) => widths.map((n) => `/img/${slug}-${n}.${ext} ${n}w`).join(', ');
  const fallback = widths[0];

  return (
    <picture data-fill={fill ? '' : undefined}>
      <source type="image/avif" srcSet={srcset('avif')} sizes={sizes} />
      <source type="image/webp" srcSet={srcset('webp')} sizes={sizes} />
      <img
        src={`/img/${slug}-${fallback}.webp`}
        alt={alt}
        width={w}
        height={h}
        className={className}
        loading={priority ? 'eager' : 'lazy'}
        decoding={priority ? 'sync' : 'async'}
        fetchPriority={priority ? 'high' : 'auto'}
        style={{
          objectPosition: position,
          backgroundImage: `url("${blur}")`,
          backgroundSize: 'cover',
          backgroundPosition: position ?? 'center',
        }}
      />
    </picture>
  );
}
