// AUTO-GENERATED by build-dish-images.mjs — do not edit by hand.
// One entry per unique photograph; several dishes can point at the same key.
import type { ImageMeta } from './images';
export const DISH_IMAGES: Record<string, ImageMeta> = {
 "2551528331": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 574,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJbACdADJ3BKn7OUAAP7Jdp2QVBj9pPC3B9errapTnfS/vCOl0gwW6iZMhKrj4ty8f5V2gQbW+OPJ7fb6ekkFQUU3sAAA"
 },
 "7bf71c8b5e": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADwAQCdASoQAAsAA4BaJbACdACThVEagUAAziHRFD2QtY9ZUOfisOmJMQfzPhx489qg43/JBmoo0FFN7AA="
 },
 "1c232dc2f3": {
  "widths": [
   480,
   360
  ],
  "w": 480,
  "h": 384,
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAACwAQCdASoQAA0AA4BaJbACdLoAAF0AAP545tmJjYIq8lAtSRiEd2AngOwTD5CU3RqWNoS0GZQTuJS8+JxN8lcCaeLG/XyKz6srJz3c4+1g+Xl4Zx8JYikm0nJH4AAA"
 },
 "000a7b8527": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 329,
  "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACQAQCdASoQAAYAA4BaJbACdABfz5gA/rD3cnLuOjZTojtL1yqhwzZw+m781j7kCSqkjwChXtdxHo2AAWQEmakHYAA="
 },
 "1b4303e967": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 454,
  "blur": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoQAAgAA4BaJbACdAENd6KuDgAA/mAMaCpCJhIkvi9pnOPQttjOhWUbONAEcoX8uRarwS577qtvmpiIAAA="
 },
 "37e3b65aa2": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 403,
  "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAQAgCdASoQAAcAA4BaJZACdAEPdGdTNNgAAPwRPZuSHKUQL742iivqWZhi9zrNyt7anc41jjG+iShH3ZO+jkmX4QEr7OXJwQAAAA=="
 },
 "01b3da3b39": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 574,
  "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsAA4BaJbACdAD1Z1WqotHuAAD5E3RzzcZ23RiioimHpDEVJLV4MEdCZSGeYQJzub91iB8Oq6e+x/J+1LK9SYDszOChYJYAGy8GMU7Y7Wh65hS1BCKVhekAAA=="
 },
 "70590d8c06": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 568,
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAsAA4BaJbACdACZ+5EIJKwAAP7FxIb+7rYquln1Nc1bQ92D0NvToD7yWcGNHaD78ZVtHxqSDLdVnhUWhFyDz58qMWoOBtfwYH7WmZ4pnWQ1BSeE5UAA"
 },
 "637059d6df": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 438,
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAgCdASoQAAgAA4BaJagCdAYrxlV/+reZMQAA/pUPTgMfTLNzY1FNCXhnkPb+9kDGyjGwM3wsExPxI2H9xKMW6AhwZnK87HR5C3k/lxNOExiWSR/2HkZMEAA="
 },
 "6d2fbd9d34": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 574,
  "blur": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABwAgCdASoQAAsAA4BaJbACdAYstgfTpSJTqBuIAP7T5y3uQYWrgxo7/qpwEj/6YyMPvvgJa0SmjN31MqYZMo3IPCqmZMwDwyPWS/EY7BGtL18h5KwfvpsvTl1syCZ5YLl94Al279W7JLB0VcLg6SAwAAA="
 },
 "8dd97726c2": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAQCdASoQAA0AA4BaJbACdADVcAAA/ufXsyiM9xtHxx6YLpxvmfcbk0ZMrCJnos6NHymp4UtsL0Klj2dvC7P15MDPu1J3QNPJZUqAAAA="
 },
 "518d23721f": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAA0AA4BaJbACdAEXTvhIc/DAAP6zNmIx0x5eAgpXmtIfbjNaAmAavp+UaEaBKmAvm1bq0xqsJw/ndA9oAIH0YQ7X+YZKlgWuEQAA"
 },
 "ada6606a7c": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAADQAQCdASoQAAsAA4BaJQBOgCPpqp/SgAD19u7mcMtNDknvE+atsALDWlLS8TU/huHRkkxOKpAAAA=="
 },
 "d32288602d": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAsAA4BaJQBOgBVB3jGAAAD+PwWqN1hXArM6JHKnoziOKP+nPkPwfmGSlBgcRo5qqxF3kmgAAA=="
 },
 "4eb2aee56c": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 738,
  "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAA4AA4BaJbACdAEff6KVuZeUAAD8y9UUDWyPtCBZRdDHXR/gaCnH+B0+VbhGFDtqEV14uRF+ntUVwKEhMTRhb9foIhEOkefKZr+nR++YM8b5wbkAAA=="
 },
 "9099c5653b": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAAsAA4BaJbACdAEP804lAAD+7gqZmwzWeejdmPrLfCwRxAfvZQY7KmDyOO9PfrbP4LEsBDeY+Kzap6Pcc3G59tbIewrp00pMGgIOgfNHeAAA"
 },
 "91552e3537": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 567,
  "blur": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQAgCdASoQAAsAA4BaJbACdAYuljq5qmgAAM4QCGtcA8K/eyKabG2GRttR9anVfEigPzRiKJ6go3XAeMmFgLZpA2urKZwQSjldXUPEsSLObYaaGtm92+HefdGvx+TQzW46dJf9gjOAAA=="
 },
 "7f8ce7c085": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAsAA4BaJbACdADo/OPdUdngAP5V9u1IBvuiuiz03ljxJ0jO0JBmyfGslZ7IgrllN1NKDKAq9cLUfVBpAnQmUIbrmAAA"
 },
 "c41b1bab49": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 468,
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJaACdAEPdl9Yv04AAP7CFFzfUyIFXOUzzAEVjmmwJ2jS3mt9FHgg/zRvPZGInml/HLjrZcybjKGo+NQrKYAA"
 },
 "a954d6602f": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 760,
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQAgCdASoQAA4AA4BaJaACdAEfmqB24G58qAAA/OTB5eIrMx8yjfDjk9pP+om5p7N4FvY5W4UwfRkFSF4UVdSxIRVEhN+9vjZ+B100o7ySZ3W/JdvRhrZRZo7EVgAA"
 },
 "28a517e803": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAsAA4BaJbACdAEN0wSni0gAAP5oT3hSChNjXtIbWJ/knQ5aWUMya7B+mDrhYNb3lUKboSXnwSX9eDZIOTmB5FKdiQAA"
 },
 "4e56ca45b2": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAsAA4BaJbACdADpNuYF84oAAP6zvIg+VZ01Tl//UO4AEZXZJZoLFd6erHJ5VPEB+PF1Kr8UiLym9Lqqnr8bm8Cl/EKoAAA="
 },
 "4ec9c464b2": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 513,
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABwAgCdASoQAAoAA4BaJZACdAEfcYWsVGuVceBgAP27k+dxMPNzcvuZ7v5mrVcStUOhw1bnqL43/5UUqoMKx45ZslS5eRv+RAekWExwqVc+PvcoFWuCCRy6AAA="
 },
 "e926d6741c": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 691,
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQAgCdASoQAA0AA4BaJbACdAEC1tupTl6AAM4CnC7rWI1KWRA0eyq2fGeZfgt1JYyZ5iZC8zE6bkrUN6Hie8uXTpzAn5LesDGkVMwTWm3AAA=="
 },
 "e63b2cb4fa": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 733,
  "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAQAgCdASoQAA4AA4BaJbACdAD1rbxs9jaQAPzjH8cUvzYpaw5a3ot4bAyr7XLMaqHaAiB7qB6Ns5k8t8NYgQWFbGHXnlK8P3HT9CtmaQ80tQQilP/8O313T8AAAA=="
 },
 "9e8d96d2c4": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 745,
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAA4AA4BaJaACdADicAiiFO+QAAD+AS3vNOQNT5TdFwdQ6BUOZnNzZBFVq81A/nWPJlsNxbScElCf4nidX30rG9nBGb/kdqjTexSWh0BAtaZCiAA="
 },
 "ca9deec255": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 706,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwAgCdASoQAA0AA4BaJbACdGaAAzLexBfGMEUAAP5oT2EMcPHZObE/2cyqPY48lpSp+2NXXvXJ3JkMoJwAXzgmieFhFnT2wChQV5xDBKwnOc+RwAA="
 },
 "507a1cefa3": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAwAgCdASoQAA0AA4BaJbACdAERC/Ddik3OAAD+B1S1/zFtBWs++ViAwFOK+fHwOzNL2kjD1gnrJYHf6f5/NEN8ikAOhaFMMselA73DMJRLfJaPd+MAAA=="
 },
 "dd9b9d0743": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 442,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAgAA4BaJagCdAEen7aOBcAAAOFSGTrlaUWokcsfls88RSt9YP5bnbSShw2i9X0USJ7PbAw5j5TXhS+H7NXV87u7jKyRaUeVwepzNkAAAA=="
 },
 "1be099d789": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 420,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoQAAgAA4BaJaACdAC948F/iADNcLCYP8e3Jq8cot+uwQZX5zP3+QBYIjH85OOaClbTl3athvj1SPL1hjUHoi2vrrOdhbBBWW+OgJhYDAAAAA=="
 },
 "88f46ce8c3": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 479,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAAkAA4BaJbACdADJW0DCuAD+lqyEct2bz5VphzG1eR7AVeHb8Sg25kV3FpLNpMoItQBIA/xanvDer/a0/J9+2QjW8PplMAA="
 },
 "eebe9dc480": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 441,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoQAAgAA4BaJagCdAYuvvvUzP4NhgDOJ8OpjvtpLSsuFxmjUfgfQ6rPsR4ysFJbQMvaRvEq85Ze4Q4j2wy6DI9fTs/fjncum9re/NIE8AA="
 },
 "af7edff89f": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 453,
  "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAgAA4BaJagCdAELXFg4SQAA9ZJsurfxyzqM6vTqLU54PiRmsU6dswJ21Sgu5Vg5XTU85Os/ml1ZECGcqaQbt4X7ryfyvEpZeHbMYfI2SkAA"
 },
 "495736517d": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 374,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAgCdASoQAAcAA4BaJbACdAYuvzXMF7YJm5AA9ZtYr79naDYWkpAEdcJ+b7nIBt1uVHxssnCiAcL10+vgRwFjWleprwN+zv5cjoCTbqtvOfAAAAA="
 },
 "0dabee6136": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 463,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAkAA4BaJbACdAD0kDSHKjqAAOJgC6L9FqkUXFOcZVx8UlCwFg01GtPZzCzoVT6xOtjXCO0iGlUYU+eP6m6RBmDwUjfw/Zq0Vo9oJYaAAA=="
 },
 "ce12f00f0e": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 474,
  "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJbACdAD2BeI2JSQA/o19IWdg++jFlRSrJil6TYYjSolT8OoFi1bC/hmhc/3ciXV9LC/dYDV+lU35ps2gAA=="
 },
 "14552c5ee4": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 405,
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAgAA4BaJbACdAEDyCILji54AAD+jaIc6mforjGJTG/h69neDaQu/axLRUJRD1mUwLUDwhiUGK+HipIjWYdJhJdgAAAA"
 },
 "aa48f42ba0": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 456,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAgAA4BaJbACdAD2Bgb0h5MAAM4jEamSRCrzmCLenPsSejT408/MRy43N8rec76I3h0W5AuY8fSc2XwO17/Z38uRAUisDiLQBObheAAAAA=="
 },
 "d9c32aa7d7": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 429,
  "blur": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADQAQCdASoQAAgAA4BaJbACdACz06p5kgD+jSAn9aF5SSY0xhO0xMDh9CwTXaFjM+798nmV4C1jhOVeryuAAA=="
 },
 "96edb6ff0b": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoQAAsAA4BaJZgCdAEPEAhZ+xAhAAD2kWRjHUAWacDLqqQq4H5J/nNJxcvPBRo9j5DcUlUbs7b2qaPUENVG3rBsZkytZ1mhg6OfJHn8QrGdcMscRKYp+lOAAAA="
 },
 "4ba9a7a8fd": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 393,
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAAcAA4BaJZACdADp3wyA57gA9Zx02NYYy7auYQgUVvJJp75crZBYtrYvlu47LJ/CPHSj1H94R+2oXq6tICq91tu7ZzzRZQAAAA=="
 },
 "c103e99cad": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 437,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAgAA4BaJZgCdAC8vJqobAD+qbv1+2QRxQ2rDAWJuadrWhqqn2PuVwoYBk5Yn/OLQ2bGja8fcMQ31UhKFftczYZUkWXh27loRAAA"
 },
 "8991acf05e": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 489,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAkAA4BaJbACdAEfxBH0iVrYAADODpENyP8GpgV39UMpPgyKgNIz2moTXxcY750EA6wFXLPPsBEHeqtgzndCDlkuzlUAAAA="
 },
 "154d601a43": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 432,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoQAAgAA4BaJbACdADpLDPsrUwAAP5IsZ75p2/7+hrv2QUzYa0+HrKtQKEVofxNUH+KYbfh3VB759dPatNdyA1uIc0ZO8QAAAA="
 },
 "acf2907adc": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 486,
  "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAkAA4BaJQBOgMW0wDrJfwAA+3NOC7VoKPztvr+OIEr4et+SZ/wtexi5Y5SavZ5CRY5KpDgH+mWHBnGXG0FEuHFAAA=="
 },
 "80f7b45932": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 468,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAkAA4BaJagCdADJRuOxmsAA3lWzFGycJ/PEkfW53T3mZ0r6bJJwtuUB8C0OdptFBazzZOZfByyxiBE/2rTXcgLPimTYAAA="
 },
 "ea592335d9": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 499,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAkAA4BaJbACdAYqNV4LNJUgAPJlREx3vbpxv2JXadpNdR7gM5fAf4vTLhomUFcWwTuK5l3Yw1VmFs/VCU31353+r6Xlc8WBKkHjOsAAAA=="
 },
 "ea526a3ae3": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 453,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoQAAgAA4BaJaACdADiZX6fSgAA+pI/Oaq/qlHbsGMsutggHX2U9k/9WKNwRbNqWFtyGmgQHROiccvR5C3k/szLBNlm7j5PwAA="
 },
 "e5744b0ade": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 392,
  "blur": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADwAQCdASoQAAcAA4BaJbACdAYtK2sh4KgA+3NMzHdJWKY2pRWucLAvGUGv49SAK5upS9jPIMASM45rlbvT2rTXccUx9CKT3AA="
 },
 "a67f5686ee": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 466,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAkAA4BaJbACdAYuHniJ9A0wAPJlRquLr2+/Pk0QYd1CUrBZ4PSMpEcEXeUrd5CoJoAs6O+UbyKFoCTGG70SHiPt3b70eC21y+O/+lIAAA=="
 },
 "34e9075c4c": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 469,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAkAA4BaJbACdAEPD3rMM8nAAP5mwONh9mJRbi1Ydeu3SP9SewmX4Ks88aLlGfkr0bMvnkP4DcojlyNH776ufN94RHTWurLzDgAA"
 },
 "df67958a36": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 429,
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAQCdASoQAAgAA4BaJbACdABV8gAA/e98MS3fOp+iiPweNuvI3KvzAOwVikn8ePxZBudGsGZzX/TD3XR4KMguCqFdVuQ3xt5QAAAA"
 },
 "6b9b8e90d6": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 487,
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAQAgCdASoQAAkAA4BaJbACdADhk0CDTlAAAPfPOmKtmKw+nif2+/0hnVd5QjyNkru3u2SYPKVqO7sHeSjd/vZ3NjrvETqy1Oj1fAAA"
 },
 "51f9a07b37": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 796,
  "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAgCdASoQAA8AA4BaJbACdGaAAks9+n+7hXuQAPzkwB41JbUzV0Vot6JCFdvnMUfBnygyTo03YksmMXzru2nXYkWHimXMGGnAdFuvITyYXTC/z4qv5Ac/CVDQgMPOtTkiDvy0d0XZBuAA"
 },
 "2bd3cd4a6e": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 780,
  "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAQAgCdASoQAA8AA4BaJbACdGaAATVTqBAAAMyJKZns8PKsjKlj6ZmotKrycttAe4NtBbEn647PaAIWxsSs7Ttg5WbN92ylzjxhHWnoU6CTRGGfmaIVf0Ojvlp8JZJ1NfZEKLmee15O1gAA"
 },
 "98e405ea10": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAsAA4BaJbACdADJ40j0jCiAAPhbMOzCelFHvFgn8zUtCzvN4D5FXq/E1wPMDx8rn7nXPG6rk2b07DAr00Hcl3PA1Z7P02Gx5MO/XQE5+oAA"
 },
 "ad9d73bb97": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 703,
  "blur": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAgCdASoQAA0AA4BaJbACdGaAwv8WuvyAPx+DY7QAAP5sQ7DhcQr9P9efkEGTrELtfyTNJF9Qvsz4QTayCpfGPNqRMxa6PgCrZzjunvHQfpX0J4/JQlJBB7bBPyICOaa+yIUhKCLCWAskdtAAAA=="
 },
 "ea4e0ea46b": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAQCdASoQAAsAA4BaJbACdAYuvhMvgAAA+PW1vGis1XjFgK8VaRU4vmGn69tXR1xdjYIwSG8cqZBYStnPzaDt8S88as+0SxZew/mp1VTKlbr1fCY+1pCzyW3iHxRucEiKuAGqAAA="
 },
 "aee3276c6b": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJagCdADhjjPNeiKqAP3rNB3PqNtUSE884O8wGpBB/O9gjTJez2tMHNhpgSKyvtIjIotHGKuPxr5LqaqVeptFhcfoDAAA"
 },
 "35435c2176": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJagCdADhjjPNeiKqAP3rNB3PqNtUSE884O8wGpBB/O9gjTJez2tMHNhpgSKyvtIjIotHGKuPxr5LqaqVeptFhcfoDAAA"
 },
 "ad9d291855": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAAsAA4BaJaACdAD1dGK61IwLQAD+4kfVCNMinAFl4aBL9ocZzRKoC8TFMg24gG/glqStC67GXJxMb7wgLQ1MDENCkeQwfYn8Q38logqeNVjSQEAAAA=="
 },
 "da3efd356a": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAsAA4BaJagCdADwpu9IAAD2tEuap/85mWHy2lYhjJfORgrdLHeqLl7+hjSbTMN3Q5qOEmh7GGvmFBp0rCez3T1m+0iku8kGamJu4sAXGMd4AAA="
 },
 "022ab16c8b": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJagCdADhjjPNeiKqAP3rNB3PqNtUSE884O8wGpBB/O9gjTJez2tMHNhpgSKyvtIjIotHGKuPxr5LqaqVeptFhcfoDAAA"
 },
 "1d1d107659": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAACwAQCdASoQAAsAA4BaJbACdAB8VawAAP7hjEtjLHnXm5qfq5evzVajJo3IGllT89/1/aKig5OWOdYfKzDlsyfnmNQ6Qv24PN36U3XrWVtZdYcgAAA="
 },
 "057709b621": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 778,
  "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoQAA4AA4BaJbACdAEf5Fgrn4sAAP7I0qan2pqe3zzuO0YYAlAcx1v7uGSLyKl/yOk/zhU/XguSLxYw6LstS17lm1zHzRcsHj+iNOY4pX6+99VfPx/FL4IhrOAAAA=="
 },
 "85083d283f": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAQCdASoQAA0AA4BaJbACdADox4yAAPk+xcOJuO3fxrZgfW70Zb0Hy2Fq+TswhMqFMuDhc1ym8IUvh71g/mtf2/rc5YZu/iMqKKe6AAA="
 },
 "655c3a24e4": {
  "widths": [
   390,
   360
  ],
  "w": 390,
  "h": 312,
  "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAQCdASoQAA0AA4BaJbACdADhzvAAAPyLd4giEa059JvV9ATGsmnba5Lw73+8x+eS3+V0/HMuxuyYL1YWuwV1x0AAAA=="
 },
 "c994953c18": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAA0AA4BaJbACdAChrzyq4AD+1zq4TEWK0gB05vW9TthCNQLe5AQjJlXS5B61DkG7MsNG16I+B3K37dV5Nq/edLejrIdGHZbZL6MdsAA="
 },
 "7ae06a9843": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABQAgCdASoQAA0AA4BaJbACdFQAAvrSo4JRJMAA/tURMnLXLvwCw8vIDXhXRIDXNVVUrKMlCbD7JAtc3/lgo04Ad1TPo063QoKoYZPXxJ1lUIAA"
 },
 "1d41b89046": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwAgCdASoQAA0AA4BaJQBOgMXc1Q992TWQAAD+566OqWH4HG6pvdDvCxOdEoH9kPlXO1czkVXC8n3z9o0S2rZbP3EGFyBozUclnKAzYIxsIAAA"
 },
 "47f6fa9f2a": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoQAA0AA4BaJbACdADjc0G5TgAA/simQFHZNLcg+a3q/z+wIFlrORn8D3b2rJZWGmB7ILaY02fr7yEX4b4TFs30ahRrJCnL7AAAAA=="
 },
 "cc12d5d7c3": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAsAA4BaJYgCdADwWNuRDfTwAP3fPH2Ko1Q4HaiWwwUxc4ExwEVHKk//HXu8KqVl72FZKmOffQ+TamNhx8UHAX+3al+M99coBeSxpTQAAA=="
 },
 "c939d68917": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 574,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAQAgCdASoQAAsAA4BaJQBOgCBbxR4PiMdAAP5qFZCXPIEyURuHZyj1NHlCjQQPyMUQ1/H3DwIX0GnLbPianB4u46vEoxdE2BFgws+MOdOkV60AAAA="
 },
 "84f349ac1f": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 574,
  "blur": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsAA4BaJYwCdAECmPtfW7r4AP6zdzbVPv2fM5+/sDjK4F4amz8yHtXRaNKlPEk1TEZzAGdFtN/WSgDzIK/alKKHuRWC36KAAAAA"
 },
 "9db460dcbf": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 574,
  "blur": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAADQAQCdASoQAAsAA4BaJYgCdAD0f+8z4AD+1/m6xSv/Rf95KpGeIKcVY7uIbV3rk9VKQ/FyfwgmdN1uYBLQEbkPyh4E7kb/3424hhdz3vCc4nVTxmdrrcArS8JCNgdD7OsAAA=="
 },
 "6e30b52f12": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoQAA0AA4BaJbACdAEQ8jFHRgD+7WTf070Fy41K4+/nlLuMS4gzNxVomXurJv+VK7iAM+BcHk9UKsmMCAAAAA=="
 },
 "56db7916f9": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAA0AA4BaJZACdAEf1S3aBNYEAAD+a+Jbqs7LsVKOOTmCcN/WOBUHT/pE7FIaB8MH6H+0S4qQ24DLfybbAaHNPosEYWVQ/BDu5QGtch/L26Q1ehUrTAAA"
 },
 "def103aa0e": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAQCdASoQAA0AA4BaJZACdAEYEcltwAD+QPc91QaY+pfAFkIS5p9H2uXLiiDShqK6DyV+xlISY2hYbgg5OasayC58F6PPYGQ3kRuk778xEWVQcn6JLQhVIczVtVhqpSbPAAAA"
 },
 "978d0a5288": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAQCdASoQAA0AA4BaJZACsADJ1T+dLngA+XbjJYQP0p5VySW8+X0UcLecd1zyAIHdKzZmW5qrTZoVJ+zdqgqBeAUAgkuaNVhxbaO5UvFzeonx5z3FVPHQHrCDQAAA"
 },
 "0e6a16d78f": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoQAA0AA4BaJYgCdADpNoLmkuiAAADyatCgqijHT8b0e5y0fe+G6nV+8pQgf3+ofqpmPx1TYnshNMVmlG3TPUhq1wAWP+LLlYk6cYz5n8hWcwBdwAA="
 },
 "2ead5b8d27": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoQAA0AA4BaJagC7ADiFvZcgADc/tjHhPHLg7N24oFVDNdNoI2xJrlreoV0hzbuTXQSm93euog5bEJrzU3SGohIL5Oys6sIInLB5LIqGAA="
 },
 "0d7f28d06a": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAQCdASoQAA0AA4BaJQBOgBnfQ3sIAADOFyNNcBcOu9IxaRgcPiUnibI2kX4Pcowai8wdUd7CHN/dY53wIoB6vmzFEm8jUHgrYcObm5P0RqOZeZAMnpygGkAAAA=="
 },
 "bab9631694": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAQCdASoQAA0AA4BaJZACdADRLK5usADONW3Pknxblf4L2QMiNF/dYwbHl/ILJjb8NyF1StmUSmzkGHtxEBVvDnDt1Qd1IqdUt8PB1S4h4gzvSa0oAAAA"
 },
 "95934a1080": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAA0AA4BaJQBOgCLpeMEiLqAA/t21D7im6dab6gsQXeX/2X6Z69dSvSY7ua4ZgOweDgkk2ftDfvZHQ4HoIwz+J1CcgAAA"
 },
 "f09aee214e": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAQCdASoQAA0AA4BaJZACdADOJJKCVADONOdiXYOX6ywD1MZsHsndK1LnFnlYdBJZd7tH0+TUGv5ks5A/U/ZJZUw9uBWIqHRjfYH0Hxcun3qAw06REec7djGYA0AA"
 },
 "2ee222677f": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoQAA0AA4BaJYgCdAEe6OOey1aWAAD86jiEKHjVibJLnS/BhREDLZvOzYRX60GOmtuxuDa04RgsPjL6IyI5QJIL6dB8XKai0H9+Gv9xK7wxflCM0kAAAA=="
 },
 "82dbf6f0f4": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAA0AA4BaJYgCdAEfqQYwAAD9vgdYALPRSjWNDWqRrrRquhdiswhwo91w0m/KuqFcfh3tBzUokX8Wuu03RQ0ahMSIAA=="
 },
 "a8bcb0da8e": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 688,
  "blur": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAgCdASoQAA0AA4BaJagCdAYvDdn58G8gAAD9nTHsDLpY7JTE6BaNwDwbFe+WcYy5I6g3vws6nMWmbyogF9gTZlq4MrqeYAvYlWiGK8By5P1YF+ytM3JHDu91UbTxtqciAAAA"
 },
 "ac99a85942": {
  "widths": [
   860,
   560,
   360
  ],
  "w": 860,
  "h": 573,
  "blur": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABQAgCdASoQAAsAA4BaJbACdAD2CTC3q9BqgkAA/sdpz5RyRup0VAOgqFTpxdQBAu2wxHbSyJwbuAiuo29W8UX4l1jO0Ntqz2tDSYCrJ1wlIV1toAA="
 }
};
export const DISH_IMAGE_OF: Record<string, string> = {
 "chicken-corn-soup-l": "7bf71c8b5e",
 "honey-garlic-fries": "1c232dc2f3",
 "spring-rolls": "000a7b8527",
 "tempura-shrimps": "1b4303e967",
 "honey-garlic-wings-6-pieces": "37e3b65aa2",
 "honey-garlic-chicken-bites": "01b3da3b39",
 "fried-fish": "70590d8c06",
 "lollipop-chicken-4-pieces": "637059d6df",
 "garlic-shrimps": "6d2fbd9d34",
 "french-fries": "2551528331",
 "dynamite-shrimps": "8dd97726c2",
 "dynamite-chicken": "518d23721f",
 "chicken-corn-soup-s": "ada6606a7c",
 "chef-special-soup-s": "d32288602d",
 "chef-special-soup-l": "4eb2aee56c",
 "sesame-shrimps-l": "9099c5653b",
 "sweet-and-sour-chicken-l": "91552e3537",
 "sweet-and-sour-shrimps-l": "7f8ce7c085",
 "sesame-chicken-l": "c41b1bab49",
 "mongolian-beef-l": "a954d6602f",
 "mongolian-chicken-l": "28a517e803",
 "kung-pao-chicken-l": "4e56ca45b2",
 "kung-pao-beef-l": "4e56ca45b2",
 "korean-chicken-l": "4ec9c464b2",
 "general-tao-chicken-l": "4ec9c464b2",
 "heavenly-white-sauce-fish-l": "e926d6741c",
 "chili-chicken-l": "e63b2cb4fa",
 "chili-beef-l": "9e8d96d2c4",
 "chicken-shashlik-l": "ca9deec255",
 "chicken-manchurian-l": "507a1cefa3",
 "sweet-sour-shrimps-s": "dd9b9d0743",
 "sweet-sour-chicken-s": "1be099d789",
 "chicken-shashlik-s": "88f46ce8c3",
 "sesame-shrimps-s": "eebe9dc480",
 "sesame-chicken-s": "af7edff89f",
 "mongolian-chicken-s": "495736517d",
 "mongolian-beef-s": "0dabee6136",
 "chicken-manchurian-s": "ce12f00f0e",
 "kung-pao-chicken-s": "14552c5ee4",
 "kung-pao-beef-s": "aa48f42ba0",
 "heavenly-white-sauce-fish-s": "d9c32aa7d7",
 "korean-chicken-s": "96edb6ff0b",
 "general-tao-chicken-s": "4ba9a7a8fd",
 "chili-chicken-s": "c103e99cad",
 "chili-beef-s": "8991acf05e",
 "egg-fried-rice": "154d601a43",
 "white-rice": "acf2907adc",
 "vegetable-rice": "80f7b45932",
 "shrimp-fried-rice": "ea592335d9",
 "chicken-fried-rice": "ea526a3ae3",
 "chef-rice": "e5744b0ade",
 "chef-s-special-chow-mein-l": "a67f5686ee",
 "chicken-chow-mein-l": "34e9075c4c",
 "shrimp-chow-mein-l": "df67958a36",
 "vegi-chow-mein-l": "6b9b8e90d6",
 "chef-special-chow-mein-s": "51f9a07b37",
 "veggie-chow-mein-s": "2bd3cd4a6e",
 "shrimp-chow-mein-s": "98e405ea10",
 "chicken-chow-mein-s": "ad9d73bb97",
 "korean-chicken-burger": "ea4e0ea46b",
 "kung-pao-chicken-burger": "ea4e0ea46b",
 "mongolian-chicken-burger": "ea4e0ea46b",
 "general-tao-chicken-burger-single": "ea4e0ea46b",
 "mushroom-beef-burger": "ea4e0ea46b",
 "general-tao-chicken-burger-trio": "aee3276c6b",
 "korean-chicken-burger-trio": "35435c2176",
 "kung-pao-chicken-burger-trio": "35435c2176",
 "mongolian-chicken-burger-trio": "35435c2176",
 "crispy-fried-chicken-burger-trio": "ad9d291855",
 "crispy-fried-chicken-burger": "da3efd356a",
 "mushroom-beef-burger-trio": "022ab16c8b",
 "beef-cheeseburger-trio": "1d1d107659",
 "beef-cheeseburger-single": "057709b621",
 "mango-lassi": "85083d283f",
 "green-apple-mocktail": "655c3a24e4",
 "watermelon-mocktail": "c994953c18",
 "peach-mocktail": "c994953c18",
 "mango-mocktail": "7ae06a9843",
 "pineapple-mocktail": "7ae06a9843",
 "blueberry-mocktail": "1d41b89046",
 "strawberry-mocktail": "47f6fa9f2a",
 "tiramisu-cake": "cc12d5d7c3",
 "ruby-cheese-cake": "c939d68917",
 "double-chocolate-cake": "84f349ac1f",
 "chocolate-mousse-cake": "9db460dcbf",
 "water": "6e30b52f12",
 "sparkling-water": "56db7916f9",
 "sprite": "def103aa0e",
 "red-bull": "978d0a5288",
 "pepsi": "0e6a16d78f",
 "fuze-iced-tea": "2ead5b8d27",
 "canada-dry-ginger-ale": "0d7f28d06a",
 "crush": "bab9631694",
 "diet-coke": "95934a1080",
 "coca-cola": "f09aee214e",
 "coca-cola-zero": "2ee222677f",
 "7up-zero": "82dbf6f0f4",
 "7up": "a8bcb0da8e",
 "tenders-with-fries": "ac99a85942"
};
