// AUTO-GENERATED by build-images.mjs — do not edit by hand.
// Widths are real encoded output widths, so srcset descriptors never lie.
export type ImageMeta = { widths: number[]; w: number; h: number; blur: string };
export const IMAGES: Record<string, ImageMeta> = {
 "hero": {
  "widths": [
   2304,
   1600,
   1000
  ],
  "w": 2304,
  "h": 1100,
  "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAABQBACdASoUAAoAPu1iqU2ppaOiMAgBMB2JZgCdMoR8eCf/vb7XfLqN8PHgAP3CmSzjMESKYZmfAXYf40ZPfWjamXm5HNHTR9Qwokk4X4EreXC0q5/rO4cfcodYqB3dhaM+HO/JnaWfkJsxitcQ/YKGpy2PcQBcPGgGIYsgXgA="
 },
 "roomwide": {
  "widths": [
   1860,
   1200,
   760
  ],
  "w": 1860,
  "h": 886,
  "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAADwAwCdASoUAAoAPu1iqU2ppaOiMAgBMB2JZgCdL46AwP1XUmEch0gAAPsZlycC2mh+tqhf8YwXiDxI1lTUjt3OyFFAnbdRoClKXyazsIoWFWTLwyuWIDLLyVmrL84aYd8GAdJdQxf+3n+43rpp0llv8J9QZtNFhxadpvjwwkZGvxPMG4gAAAAA"
 },
 "spread": {
  "widths": [
   1282,
   900
  ],
  "w": 1282,
  "h": 1016,
  "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAwBACdASoUABAAPu1iqU2ppaOiMAgBMB2JbACdLwABhrXi26iXbxl3ewAA+EQypCFFavECC6T8TDM/Sa9dCggn7t2ICKFa4Q5puEVwyvMDxEUA7FVF2tZB9fFNczWFG2UXvHCvLT9SU3WlHSHX0Zt4xAaXXpXteAXuDIi7cZpW883FIe1FzW/n0QAAAA=="
 },
 "sesame": {
  "widths": [
   1400,
   900,
   560
  ],
  "w": 1400,
  "h": 719,
  "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACQBACdASoUAAoAPu1iqU2ppaQiMAgBMB2JaACdMoHgAAaTh5XE8ze4r4+JBwAA8jZxf029fHvpyXJXnZ/LFvJvgxaoq7xZSxEqHPUjADJm1zKLDwdr5ODWqKunWaVMrMuMMKrA/PYiEpH9KuizuNhpS8alRYpa7CVlSYTdmAg0ykAA"
 },
 "chili": {
  "widths": [
   1400,
   900,
   560
  ],
  "w": 1400,
  "h": 712,
  "blur": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQBACdASoUAAoAPu1iqU2ppaOiMAgBMB2JZgCdAB0/2DoLfbuWpdawdeQAAP5zB5UOioHCst2Ai+7KQKuCjcVcqdY8qvvt4enwUl50K1QvQuTkj62SJt1fSmuPjo24EFjJlGqk7wXYdDrtGiTPQ/i7km+AAA=="
 },
 "beef": {
  "widths": [
   1400,
   900,
   560
  ],
  "w": 1400,
  "h": 1238,
  "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADwBACdASoUABIAPu1urlIppiQiqAgBMB2JQBYj4wnAAiUN8adfbwMP9eQiDBabogAA/esNwtHsvCFAh7Y19bxiCl7erosXFRrNk6xeoqbUzBgYEr581hbpqKqlB2G5Rf0Krj642jFI+5sb+EgG6OXwa19WgGtkvyUe4HGcHgqi0NAGk9D3AgAKXAAAAA=="
 },
 "kungpao": {
  "widths": [
   1400,
   900,
   560
  ],
  "w": 1400,
  "h": 933,
  "blur": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaACdABK4ZaEnmFZsAAD+jcqmMFwMzyBpqrUlrBziNFNXJsGB1IejnxOBgyTlQggQs+kEd71CRu78dJpq9IMeIRPbyXMGOWN8oAgVU2v3OwAA"
 },
 "chowmein": {
  "widths": [
   1400,
   900,
   560
  ],
  "w": 1400,
  "h": 758,
  "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBACdASoUAAsAPu1iqU2ppaOiMAgBMB2JbACdMoR3AdA0b9YVHj9RVKygAPRWYGyRrjO6aQKNTgAL/0aVRBtoZMxP37wog1o0TQbmohjGN69Ujrrtxk9vtaKkM3pE/65MU4NfHdGG+plw6LzmJQ/qouNO903XzMwNKbOXJY0kc4Nng1dUAA=="
 },
 "burger": {
  "widths": [
   1400,
   900,
   560
  ],
  "w": 1400,
  "h": 933,
  "blur": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JbACdMoRwACXAa+L9k/+/Wq8AAPgp8+HvBDTqeISKFFkxprqMUadO92EZxwCE9XzX0gqZC9GYGrUWLKp+ANrhASVrzrnP2NLc45eil1bKJQJvcMQzKpJ2Jxnv5c0qCqJ4XZC22C8UqRZteAAAAA=="
 },
 "room": {
  "widths": [
   2000,
   1400,
   900
  ],
  "w": 2000,
  "h": 1333,
  "blur": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JagCdG1/ARMBe1TB3zR9EEAD+woWrBlR4R9cAJXT57xpEg2feLYkyrm/X4HExbbo6fRDsvPs2uxklXNohyPEOpolmZ1wp3Ib/4bxns4b4irIzsN4d4hMt4QVs1+1FNffi8UH9ZIb4ibsjJ7Ij4AAA"
 },
 "table": {
  "widths": [
   1600,
   1100,
   700
  ],
  "w": 1600,
  "h": 2400,
  "blur": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAADQBQCdASoUAB4APu1ep06ppKMiMBgMATAdiWgAuyDBSf4B6+/bDp0cfBvlu3mSazF54+94OSgAAP6JJ8PRWY3/DVX2cn8nFZW7PRu6eY0zPrdZVhJ0NibGxmAIkgdxFU5Vhw1SSGAqUn6+nDxuRXyKxZzjX3YADG6962v3olINEeRh0i8T6LQv1Qw8Wgx7v8u/DiPtZMwUVDNoTNqMhyTIATxOoPBThagVIk8yWdaQqHpdMqunRlfzylEeIN+D1W1ppG+ftHB/sxaoYAAAAA=="
 },
 "detail": {
  "widths": [
   1600,
   1100,
   700
  ],
  "w": 1600,
  "h": 2400,
  "blur": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAADQBQCdASoUAB4APu1kqk+ppSOiMBgIATAdiWMAuyFuif4tnc26hPm3P5p22bi4gcJv3vTfbWfwAP7uiE5B7fetd5rnbtA/G+rL6bCdMebMzXRikECJfTA5bYRPbjh6uJO5PcpoBzTyjgD1C8IOPXiwnfEid8itrp9JpRZlZu7XkqZGBnMdM76SHsPY01WsGXa7IX77FYxNHC/Bt0+lnr6f+kwF+RKzZTR1F53uXe3/HyR2t9Q+jjg3cU2bMkd35/AWeAnuNwwzV2HHBIw1YrU/F7J8QuIJuA9+HqXqLSMAAA=="
 }
};
export type ImageSlug = keyof typeof IMAGES;
